# Generated by Django 3.2.5 on 2021-07-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tms',
            name='places',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
