# Generated by Django 3.2.5 on 2021-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0002_tms_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='tms',
            name='colonnes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tms',
            name='rangee',
            field=models.IntegerField(default=30),
        ),
    ]
