# Generated by Django 3.2.5 on 2021-07-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_auto_20210722_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tms',
            old_name='colonnes',
            new_name='columns',
        ),
        migrations.RenameField(
            model_name='tms',
            old_name='rangee',
            new_name='rows',
        ),
        migrations.RenameField(
            model_name='tms',
            old_name='places',
            new_name='seats',
        ),
    ]
