# Generated by Django 3.2.5 on 2021-07-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0004_auto_20210722_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tms',
            old_name='description',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='tms',
            old_name='title',
            new_name='classroom',
        ),
    ]
